BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "PK_storychords" (
	"pkid_storychords"	TEXT,
	"pk_tablature_cues"	TEXT,
	"storychords_timbre"	TEXT,
	"storychords_articulation"	TEXT,
	"storychords_tempo"	TEXT,
	"storychords_definition"	TEXT,
	"storychords_illustration"	TEXT,
	"storychords_explanation"	TEXT
);
CREATE TABLE IF NOT EXISTS "PK_tablature" (
	"pkid_tablature"	INTEGER,
	"case_number"	TEXT,
	"pkid_storychords"	INTEGER,
	"tablature_title"	TEXT,
	"tablature_summary"	TEXT,
	"anime_case_title"	TEXT,
	"anime_tablature_title"	TEXT,
	"anime_tablature_summary"	TEXT,
	PRIMARY KEY("pkid_tablature")
);
INSERT INTO "PK_storychords" VALUES ('SP0001','4, 68','Dynamics','Resolve','Steadfast','Vivian ultimately
retains her essential
nature',NULL,'Every Main Character represents one special character element. This element is either the cause of the story''s problem, or its solution. The Main Character cannot be sure which she represents since it is too close to home. Near the climax of the story, the Main Character must make a Leap of Faith and decide if she should stick with her approach in the belief that it is the solution, or jump to the opposite trait in the belief she has been wrong. When a Main Character sticks with her story-long approach, she is said to remain Steadfast.');
INSERT INTO "PK_storychords" VALUES ('SP0002','72','Dynamics','Growth','Stop','regarding Vivian, the
audience is waiting for
something to end',NULL,'The nature of a Main Character''s growth always has a direction to it. If the Main Character is a change and stop character, she will grow through change by abandoning a detrimental characteristic which she is presently exercising. If the Main Character is a steadfast and stop character, she will grow in her resolve to hold out for some negative force outside of himself to finally stop. Because both cases require the cessation of an activity (either in the character or her environment) the direction of growth is said to be Stop.');
INSERT INTO "PK_storychords" VALUES ('SP0003','16','Dynamics','Approach','Do-er','Vivian looks for a
physical solution to
her problem',NULL,'Every Main Character will have a preference to deal with problems by either physical effort or by mental/emotional effort. When a Main Character prefers working in the external environment, she is a Do-er.');
INSERT INTO "PK_storychords" VALUES ('SP0004',NULL,'Dynamics','Problem-Solving Style','Intuitive','Vivian uses intuitive
problem solving
techniques',NULL,'A choice of intuitive creates a Main Character whose psychology is based on assessing balance. The intuitive Main Character resolves inequities by comparing surpluses to deficiencies. The manner employed in resolving the inequity will involve creating a surplus where a surplus is desired, creating a deficiency where a deficiency is desired, creating a surplus so a deficiency is felt elsewhere, creating a deficiency so a surplus will be felt elsewhere. Through the application of one''s own force, hills and valleys can be created and filled either to directly address the inequity or to create a change in the flow of energies that will ultimately come together in a new hill or disperse creating a new valley. These are the four primary inequity-resolving techniques of an intuitive problem-solving style character. It is important to note that these techniques are applied both to others and to oneself. Either way, manipulating surplus and deficiency describes the approach. When selecting intuitive or logical, typically, the choice is as simple as deciding if you want to tell a story about a woman or a man. But there is another consideration that is being employed with growing frequency in modern stories: putting the psyche of one sex into the skin of another. This does not refer only to the "sex change" comedies, but to many action stories with logical problem-solving style female Main Characters (e.g. Aliens) and many decision stories with intuitive problem-solving style male Main Characters (e.g. Prince of Tides and The Hunt for Red October). When an author writes a part for a woman, he would intuitively use the intuitive psyche for that character. Yet, by simply changing the name of the character from Mary to Joe and shifting the appropriate gender terms, the character would ostensibly become a man. But that man would not seem like a man. Even if all the specific feminine dialog were changed, even if all the culturally dictated manifestations were altered, the underlying psyche of the character would have the intuitive, female bias, rather than the logical, male bias. Sometimes stereotypes are propagated by what an audience expects to see, which filters the message and dilutes the truth. By placing the intuitive psyche in a male character, preconceptions no longer prevent the message from being heard. A word of caution -- this technique can make a Main Character seem "odd" in some hard to define way to your audience. So although the message may fare better, empathy between your audience and your Main Character may not.');
INSERT INTO "PK_storychords" VALUES ('SP0005','13','Dynamics','Driver','Action','in terms of the Overall
plot, actions force
decisions',NULL,'All stories have both Action and Decision, however one will take precedence over the other. Traditionally, one might define an Action story as having more Action or more intense Action than a Decision story. This view is overly influenced by how the story is told rather than what it represents. Dramatica takes a different view of Action and Decision. Either Actions force the need for Decisions or Decisions force the need for Actions in order to advance the plot. Over the course of the story as a whole, if Actions precipitate the progression of the plot, it is an Action story. The question to ask in regard to any particular story is which comes first to move the story along?--not which is there more of, for even if Action kicks things off, a small Action may be followed by great quantities of deliberation. In such a story, although Action is the Driver, one would hardly call it an Action story in the traditional sense. Action stories will begin with an Action, be marked at the beginning and end of every Act by an Action, and will end with a climactic Action. In an Action story, the story will eventually slow and dwindle until another Action occurred.');
INSERT INTO "PK_storychords" VALUES ('SP0006','47','Dynamics','Limit','Optionlock','the story climax occurs
because all options
have been exhausted',NULL,'If not for the story being forced to a climax, it might continue forever. When a story is brought to a conclusion because the characters run out of options, it is said to contain an Optionlock. As an analogy, one might think of a story as the process of examining rooms in a mansion to find a solution to the story''s problem. Each room in the mansion will contain a clue to the actual location of the solution. In an optionlock, a character might be told he could examine any five rooms he wanted, but only five. He must pick the five rooms ahead of time. He can take as long as he likes to search each one, and go thoroughly examine four of the rooms. After the fourth he is given a choice: based on the clues he has found so far, does he wish to stick with his original fifth choice or pick another room instead out of all that remain. Either choice may lead to success or failure, but because running out of options forced the choice it is an Optionlock story. The choice is the Optionlock leap of faith that determines Change or Steadfast.');
INSERT INTO "PK_storychords" VALUES ('SP0007','71','Dynamics','Outcome','Failure','the original goal is not
achieved',NULL,'Every overall Throughline in a Grand Argument Story has at its beginning a desired outcome to be sought after. Ultimately, the characters will either achieve that outcome or Fail to do so. The reasons for Failure (and in fact the Failure itself) may not be bad. For example, in the course of trying to arrive at an outcome, the characters may decide it was wrong to want it, or learn that achieving it would hurt people. Whatever the reason, be it nobility or no ability, if the outcome desired at the story''s beginning is not achieved, the story ends in Failure.');
INSERT INTO "PK_storychords" VALUES ('SP0008','72','Dynamics','Judgement','Good','Vivian ultimately
succeeds in resolving her personal problems',NULL,'Even though the effort to achieve the story''s goal may result in success, this is not necessarily a good thing for the Main Character. In fact, success might be obtained in the overall story even though the Main Character fails to resolve her personal problems. Similarly, the effort to achieve the story goal might end in failure, yet the Main Character ends up overcoming her personal problems. Regardless of whether the overall story ends in Success or Failure, if the Main Character succeeds in resolving her personal problems, the outcome is deemed Good.');
INSERT INTO "PK_storychords" VALUES ('SP0009','4','Synopsis','Throughline',NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0010','2','Overall Story Throughline','Throughline','Activity','the geeneral area in which the Overall Story''s problem resides as it concerns an activity or endeavor',NULL,'The Activity Class is one of action. Whereas the Situation Class describes a fixed situation, Activity is a Class of dynamics. Situations evolve, develop, and change. Activities are engaged in and endeavors undertaken.');
INSERT INTO "PK_storychords" VALUES ('SP0011','2','Overall Story Throughline','Concern','Understanding','the area of shared concern in the Overall Story as it concerns appreciating the meaning of something',NULL,'Understanding is different from knowledge. From knowledge one gets awareness, from Understanding, one gets meaning. To obtain meaning requires not only knowing the substance of its nature, but the context of its essence. In other words, one must not only define what something is, but how it fits into the larger picture as well. To this end, Reason describes the function and Emotion defines the purpose. So Understanding is not just an intellectual pursuit, but requires an empathy with the meaning as well. It is useful to note that many Eastern and ancient philosophies define Understanding as "becoming one with" that which is being considered. Until one joins a subject in unity, one cannot understand it.');
INSERT INTO "PK_storychords" VALUES ('SP0012','5','Overall Story Throughline','Issue','Conditioning','the Overall Story''s thematic focus as it concerns responses based on experience or training',NULL,'Conditioning describes the learned responses to various stimuli. Similar to Instinct in that the Consciousness in not involved until after the fact, Conditioning differs insofar as it was not inherent in the basic nature of a character, but acquired though training or familiarity to impose its triggers on the mind. Since Instincts are intrinsic, and Conditioning is learned, they frequently come in conflict over how to respond. This concept alone has provided the theme for many intriguing stories.');
INSERT INTO "PK_storychords" VALUES ('SP0013',NULL,'Overall Story Throughline','Couterpoint','Instinct','the Overall Story''s thematic rebuttal as it concerns intrinsic unconditioned responses',NULL,'Instinct describes those built- in responses to situations and circumstances that are not learned, yet drive one to comply with one''s urges. How much sway they have over an individual depends both upon the nature of the instinct and the intensity of conditioning against the instinct that he has experienced by accident, design, or choice. When one acts or responds according to instinct, there is no conscious consideration beforehand. Only after the fact does the consciousness become aware that an instinct has been triggered. Nonetheless, one can learn to inhibit instinctual commands until the consciousness has the opportunity to consider the propriety of conforming to it.');
INSERT INTO "PK_storychords" VALUES ('SP0014',NULL,'Overall Story Throughline','Thematic Conflict','Conditioning','the Overall Story''s thematic comparison as it balances Conditioning against Instinct',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0015','6, 9','Overall Story Throughline','Problem','Inertia','the source of the Overall Story''s difficulties as it concerns continuation of a state or process',NULL,'Inertia is a tendency to maintain the status quo. That which is moving wants to keep moving. That which is at rest wants to stay at rest. An Inertia-oriented character concerns himself with keeping things on an even keel. He tries to avoid or prevent anything that rocks the boat. He also does not adapt well to change.');
INSERT INTO "PK_storychords" VALUES ('SP0016','67','Overall Story Throughline','Solution','Change','the actual remedy for the Overall Story''s problem(s) as it concerns an alteration of a state or process',NULL,'Change is the force that alters. A characteristic representing change is quick to adapt but also cannot leave well enough alone. It feels that if things have been one way long enough to establish a pattern, its time to change it.');
INSERT INTO "PK_storychords" VALUES ('SP0017','19, 21','Overall Story Throughline','Symptom','Projection','the principal symptom of the Overall Story''s problem(s) as it concerns an extension of probability into the future',NULL,'Projection is a means of anticipating events and situations by extending the line of how things have been happening into the future. A character that represents Projection has a good grasp of what he might look for in things to come. However, this character will give great weight to past experience, so abrupt changes in direction might be ignored until it is too late.');
INSERT INTO "PK_storychords" VALUES ('SP0018','45','Overall Story Throughline','Response','Speculation','the apparent remedy for the principal symptom of the Overall Story''s problem(s) as it concerns an extension of possibilities into the future',NULL,'Speculation is the effort to determine what could conceivably happen in the future, even though it is not the most likely scenario. Speculation leads a character to expect the unlikely in the event that it actually occurs. Difficulties arise when Speculation runs rampant and a character puts effort into preparing for things that are so unlikely as to be unreasonable or improbable.');
INSERT INTO "PK_storychords" VALUES ('SP0019','7, 20, 47','Overall Story Throughline','Benchmark','Doing','the standard by which progress is measured in the overall Story as it concerns engaging in a physical activity',NULL,'Doing is the process of being physically active. In and of itself, Doing does not require any purpose, but simply describes engaging in a process, task, or endeavor, whether for pleasure or by necessity or compulsion.');
INSERT INTO "PK_storychords" VALUES ('SP0020','13, 23','Overall Story Throughline','Catalyst','Senses','the kind of intem which serves to push the Overall Story forward as it concerns sensory observations',NULL,'Senses refers to the raw data supplied to the mind to interpret. Sometimes the data is accurate, other times it is faulty even before the mind gets hold of it. Senses then, describes the overall accuracy of an observation (such as seeing a crime or checking the results of a test). When taken in conjunction with its Dynamic Pair of Interpretation, all manner of error or accuracy can be created. This provides the author with a powerful storytelling tool to create comedies and tragedies based in error and misunderstanding.');
INSERT INTO "PK_storychords" VALUES ('SP0021','19, 33, 53, 63','Overall Story Throughline','Inhibitor','Fate','the kind of item which serves sto impede the Overall Story''s progress as it concerns a future situation that will befall an individual',NULL,'The distinction between Fate and destiny is an important one. Destiny is the direction one''s life must take, Fate is any given moment along that direction. So whereas one can have many Fates, one can only have one destiny. Fate describes a state of situation and circumstance that exists at a particular point in time. In other words, Fate is something of an outcome, or perhaps a step - just one of a number of Fates along the path of one''s destiny. Characters often either make the mistake of assuming that they have only one Fate and are therefore stuck with it, or they mistakenly believe they can achieve their destiny without "passing through" unattractive fates that lie along the path. The nature of a Fate is that no matter how you try to avoid it, it tracks you. All options that you might exercise still lead to that Fate. That is what also defines Destiny as the limitations on free will that force you to arrive at your Fate no matter how you alter what you do or what kind of person you are. If we all knew the future, there would be no freewill.');
INSERT INTO "PK_storychords" VALUES ('SP0022','9','Synopsis','Main Character Backstory','Vivian''s backstory is an intricate spectral lattice, woven from violence, stolen futures, and betrayals too intimate to escape. Rather than a linear history, it manifests as a living shadow accompanying every decision she makes. It traps her within the Inertia she despises in the MODS while ironically pushing her closest to the Change she cannot accept. In ASTRO7EX, her backstory is not simply her "why," but the phantom co-pilot she cannot eject — making her both architect and prisoner of her story.','the occurances from Vivian''s past which account for the personal problems with which she begins the story',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0023','3','Main Character Throughline','Throughline','Situation','the realm of Vivian''s personal journey and growth as it concerns a situation or envirionment',NULL,'The Situation Class is where any fixed state of affairs is explored, such as an institution, system, or situation that remains stable and unchanging. The point may be to show that the system is good, bad, or neutral, but the focus must be on the system, not on how the system is changing.');
INSERT INTO "PK_storychords" VALUES ('SP0024','3','Main Character Throughline','Concern','The Past','the issue or issues held in greatest importance by Vivian as it concerns what has already happened',NULL,'The Past is not unchanging. Often we learn new things that change our understanding of what past events truly meant and create new appreciations of how things really fit together. A Story that focuses on The Past, may be much more than a documentation of what happened. Frequently, it is a reevaluation of the meaning of what has occurred that can lead to changing one''s understanding of what is happening in the present or will eventually happen in the future.');
INSERT INTO "PK_storychords" VALUES ('SP0025','66','Main Character Throughline','Issue','Destiny','Vivian''s personal thematic focus, topic, or value standard as it concerns the future path an individual must take',NULL,'Destiny is the path to a particular fate, or through a series of fates. Fates are experiences or conditions one must encounter along the way as one''s Destiny directs one''s course. The nature of Destiny is such that no matter how much a character is aware of the nature and location of an undesirable fate, nothing he can do is enough to pull him off the path. Characters often try to deny Destiny by jumping to an entirely different path, only to discover that all roads lead to Rome.');
INSERT INTO "PK_storychords" VALUES ('SP0026',NULL,'Main Character Throughline','Thematic Counterpoint','Fate','the thematic opposite ot the area of Vivian''s greatest sensitivity as it concerns a future situation that will befall an individual',NULL,'The distinction between Fate and destiny is an important one. Destiny is the direction one''s life must take, Fate is any given moment along that direction. So whereas one can have many Fates, one can only have one destiny. Fate describes a state of situation and circumstance that exists at a particular point in time. In other words, Fate is something of an outcome, or perhaps a step - just one of a number of Fates along the path of one''s destiny. Characters often either make the mistake of assuming that they have only one Fate and are therefore stuck with it, or they mistakenly believe they can achieve their destiny without "passing through" unattractive fates that lie along the path. The nature of a Fate is that no matter how you try to avoid it, it tracks you. All options that you might exercise still lead to that Fate. That is what also defines Destiny as the limitations on free will that force you to arrive at your Fate no matter how you alter what you do or what kind of person you are. If we all knew the future, there would be no freewill.');
INSERT INTO "PK_storychords" VALUES ('SP0027',NULL,'Main Character Throughline','Thematic Conflict','Destiny','the thematic comparison within Vivian as it balances Destiny agaainst Fate',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0028','3','Main Character Throughline','Problem','Aware','the source of Vivian''s drive',NULL,'In ASTRO7EX, Vivian’s Problem of Aware transforms from an edge in combat to a core vulnerability. Her hyper-awareness is both a narrative weapon and a spiritual curse—she sees too much to function in any traditional sense. Rather than becoming enlightened, she becomes alienated, unmoored from consensus reality. Her journey is not about closing her eyes but about finding the courage to act regardless of infinite contradictory inputs. Her final resistance is not in “understanding more,” but in choosing to move forward without further proof.');
INSERT INTO "PK_storychords" VALUES ('SP0029','68','Main Character Throughline','Solution','Self Aware','what is needed to truly satisfy Vivian''s drive',NULL,'Vivian’s Solution of Self Aware transforms her narrative from a surveillance operator to an existential warrior. By integrating her perceptions and failures into her sense of self, she transcends the need for external verification or systemic coherence. Her final acts are no longer aimed at exposing or fixing the world but at asserting the sovereignty of her identity in defiance of a universe that refuses to validate her. In the end, she becomes her own proof.');
INSERT INTO "PK_storychords" VALUES ('SP0030',NULL,'Main Character Throughline','Symptom','Projection','the area or item Vivian believes the problem to be as it concerns an extension of probability into th efuture',NULL,'Projection is a means of anticipating events and situations by extending the line of how things have been happening into the future. A character that represents Projection has a good grasp of what he might look for in things to come. However, this character will give great weight to past experience, so abrupt changes in direction might be ignored until it is too late.');
INSERT INTO "PK_storychords" VALUES ('SP0031',NULL,'Main Character Throughline','Response','Speculation','the response of Vivian to her apparent problems as it concerns an extension of possibilities into the future',NULL,'Speculation is the effort to determine what could conceivably happen in the future, even though it is not the most likely scenario. Speculation leads a character to expect the unlikely in the event that it actually occurs. Difficulties arise when Speculation runs rampant and a character puts effort into preparing for things that are so unlikely as to be unreasonable or improbable.');
INSERT INTO "PK_storychords" VALUES ('SP0032','21','Main Character Throughline','Benchmark','How Things are Changing','the standard by which Vivian''s degree of growth is indicated as it concerns the way things are going',NULL,'How Things are Changing concerns itself with change: what direction and how fast? It is not so important where things were, are, or will be, but rather how the struggle between inertia and change seesaws over the course of the story.');
INSERT INTO "PK_storychords" VALUES ('SP0033','71','Main Character Throughline','Unique Ability','Prediction','the quality that makes Vivian uniquely qualified to resolve the story''s problem as it concerns predetermination of a future state of affairs',NULL,'Prediction explores the effort to learn the course of one''s destiny. Destiny is the path to a particular fate, or through a series of fates. Fates are experiences or conditions one must encounter along the way as one''s destiny directs one''s course. The nature of destiny is such that no matter how much a character is aware of the nature and location of an undesirable fate, nothing he can do is enough to pull him off the path. However, if one could know the future course, one could prepare for each eventuality in order to minimize or maximize its effect.');
INSERT INTO "PK_storychords" VALUES ('SP0034','3, 41','Main Character Throughline','Critical Flaw','Instinct','the quality that inhibits or undermines Vivian''s effectiveness, specifically her Unique Ability as it concerns intrinsic unconditioned responses',NULL,'Instinct describes those built- in responses to situations and circumstances that are not learned, yet drive one to comply with one''s urges. How much sway they have over an individual depends both upon the nature of the instinct and the intensity of conditioning against the instinct that he has experienced by accident, design, or choice. When one acts or responds according to instinct, there is no conscious consideration beforehand. Only after the fact does the consciousness become aware that an instinct has been triggered. Nonetheless, one can learn to inhibit instinctual commands until the consciousness has the opportunity to consider the propriety of conforming to it.');
INSERT INTO "PK_storychords" VALUES ('SP0035',NULL,'Synopsis',NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0036',NULL,'Impact Character Throughline','Throughline','Fixed Attitude','the general area in which MODS operates as it concerns a fixed attitude or outlook',NULL,'The Fixed Attitude Class describes a fixed attitude. This can be a bias, prejudice or even a "positive" opinion about anything at all. The key is that the attitude is fixed, meaning it is accepted as a given and not reevaluated. Often the Fixed Attitude Class is represented by a group of people who share a common bias for or against something.');
INSERT INTO "PK_storychords" VALUES ('SP0037','18','Impact Character Throughline','Concern','Memories','MOD''s primary objective or purpose as it concerns recollections',NULL,'The Past is an objective look at what has happened. In contrast, Memories is a subjective look at what has happened. Therefore, Memories of the same events varies among individuals creating many different and possibly conflicting recollections. Often one''s current feelings come from memories, both pleasant and unpleasant. Many a taut story revolves around a character''s effort to resolve open issues from his memories by recalling or forgetting them.');
INSERT INTO "PK_storychords" VALUES ('SP0038',NULL,'Impact Character Throughline','Issue','Falsehood','the area of MODS''s greatest impact as it concerns that whihc has been shown to be erroneus',NULL,'Falsehood does not mean incorrect, but in error. In other words, what is presented may be absolutely accurate and yet not reflect what is really going on. Perhaps only a portion of the truth is expressed, or more information than is pertinent causes one to misconstrue. A danger is that Falsehood can get away from the control of its creator. Once an error has been passed off as truth, some will continue to accept it as truth, even if it is recanted by the person that gave the False account.');
INSERT INTO "PK_storychords" VALUES ('SP0039',NULL,'Impact Character Throughline','Thematic Counterpoint','Truth','the thematic comparison of MODS''s impact as it concerns that which is actually correct',NULL,'Truth is more than facts and accuracy. Truth is meaning. Whenever someone is quoted out of context, what is reported may be factual and may be accurate, but it is not Truthful. Meaning depends upon intent and purpose. That is the beauty of the legal system: that even if someone is caught red-handed, the jury can acquit him because it feels there were mitigating circumstances. The problem with Truth is that it is an interpretation, and therefore open to debate. One person''s Truth is another''s Falsehood.');
INSERT INTO "PK_storychords" VALUES ('SP0040',NULL,'Impact Character Throughline','Thematic Conflict','Falsehood','the thematic comparison of MODS''s impact as it balanses *Falsehood* against *Truth*',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0041',NULL,'Impact Character Throughline','Problem','Inertia','the nature of MODS''s drive as it concerns a continuation of a state or process',NULL,'Inertia is a tendency to maintain the status quo. That which is moving wants to keep moving. That which is at rest wants to stay at rest. An Inertia-oriented character concerns himself with keeping things on an even keel. He tries to avoid or prevent anything that rocks the boat. He also does not adapt well to change.');
INSERT INTO "PK_storychords" VALUES ('SP0042',NULL,'Impact Character Throughline','Solution','Change','the item, event, or process needed to truly satisfy MODS''s drive as it concerns an alteraton of a state or process',NULL,'Change is the force that alters. A characteristic representing change is quick to adapt but also cannot leave well enough alone. It feels that if things have been one way long enough to establish a pattern, its time to change it.');
INSERT INTO "PK_storychords" VALUES ('SP0043',NULL,'Impact Character Throughline','Symptom','Order','the area in which MODS believes the problem can be resolved as it concerns a patterned arragement',NULL,'The character containing the Order characteristic is concerned with keeping things organized. Change is not a problem as long as it is orderly. However, sometimes you can''t get there from here and the whole system has to be blown apart to rebuild from the ground up. Sometimes a little chaos needs to reign so that a logjam can be broken or a process speeded up. The character representing Order is an organization fiend.');
INSERT INTO "PK_storychords" VALUES ('SP0044',NULL,'Impact Character Throughline','Response','Chaos','MODS''s point of attack as it concerns random change or lack of order',NULL,'Chaos is disorder, randomness, anarchy. The Chaos characteristic is brilliant at cutting through a Gordian knot. But then it just keeps cutting every rope it sees until the chandelier falls on its head. It "stirs the pot" just to see what will bubble up to the top.');
INSERT INTO "PK_storychords" VALUES ('SP0045','17','Impact Character Throughline','Benchmark','Impulsive Responses','the standard by which MODS''s impact is measured as it concerns innate responses',NULL,'Built into the mind is an instinctual base of reactions and attitudes that cannot be altered but merely compensated for. When a story''s problem revolves around the unsuitability of someone''s essential nature to a given situation or environment, the central issue is Impulsive Responses. The solution lies in the character conditioning himself to either hold his tendencies in check or develop methods of enhancing areas in which he is naturally weak in reason, ability, emotion, or intellect.');
INSERT INTO "PK_storychords" VALUES ('SP0046','57','Impact Character Throughline','Unique Ability','Evidence','the quality that makes MODS uniquely qualified to pressure Vivian to change her nature as it concerns imformation supporting a belief',NULL,'Evidence is information one gathers to develop an understanding about something. When looking at Evidence, a character does not necessarily have to know exactly what he is looking for, just that the information pertains to the nature of what he is trying to learn about. As a result, he tends to examine the Evidence only in terms of whether or not it is something that falls into a predetermined category. Therefore, errors can occur when the Evidence (although it pertains to the subject of interest) actually holds much more information in another area. This can lead a character to "not see the forest for the trees" because he is looking at the small picture and ignoring the big one. For example, in a mystery, a detective may be looking for Evidence of who committed a murder, when in truth the victim died of natural causes, which is clearly indicated if the detective had only thought to look for that.');
INSERT INTO "PK_storychords" VALUES ('SP0047','50','Impact Character Throughline','Critical Flaw','State of Being','the quality that inhibits or undermines MODS''s impact as it concerns one''s true nature',NULL,'State of Being describes the actual nature of a character. The character himself is often not aware of the true nature of his being. In fact, there may be no one at all who fully understands all that he is. However, in the communication between Author and Audience, the essence of a character must be fully explained or the story''s message will be obscured.');
INSERT INTO "PK_storychords" VALUES ('SP0048',NULL,'Synopsis',NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0049','12','Main vs Impact Story Throughline','Throughline','Manipulation','the geenral area of difficulty between Vivian and MODS as it concerns a manner of thinking or demeanor',NULL,'The Manipulation Class is where the evolution or change in an attitude is explored, unlike the Fixed Attitude Class which describes the nature of a fixed state of mind. This is a more deliberation-oriented Class where the focus is not on the attitude itself, but whether it is changing for better or for worse.');
INSERT INTO "PK_storychords" VALUES ('SP0050','12','Main vs Impact Story Throughline','Concern','Develolping a Plan','the topic of contention between Vivian and MODS as it concerns visualizing how an existing idea might be implemented',NULL,'Developing a Plan means coming up with a practical implementation of an idea. It is not enough to simply have the idea. To conceptualize, one must develop an actual mental model of how such an idea might be made manifest. In other words, one might have an idea to build a spacious house. But to conceptualize the house, one must imagine everything that makes up the house -- the design, the layout, the colors & textures, everything that is essential to understanding what that specific house is. Developing a Plan requires being able to visualize something as a whole.');
INSERT INTO "PK_storychords" VALUES ('SP0051','18','Main vs Impact Story Throughline','Issue','Sense of Self','the Main vs. Impact Story''s thematic focus as it concerns one''s percption of oneself',NULL,'Simply put, Sense of Self is our own Self Image. A character may not truly know who he is, but he always knows who he thinks he is. This inward-looking view may be right on the mark or not even close. The difficulty a character has is that from inside himself it is impossible to be sure who he is. All he can do is take clues from the reaction of those around him. Interesting storytelling sometimes places a character among those who provide a warped feedback that creates a false Sense of Self in the character. This erroneous image may be far better, far worse, or simply different than his actual state of being. Other stories force a character to come to grips with the fact that he is wrong about himself, and the opinions of others are accurate. In a Main Character, the differential between Sense of Self and State of Being is part of what separates the Main vs. Impact from the Overall story lines.');
INSERT INTO "PK_storychords" VALUES ('SP0052',NULL,'Main vs Impact Story Throughline','Thematic Conterpont','State of Being','the Main vs Impact Story''s thematic comparison as it concerns one''s true nature',NULL,'State of Being describes the actual nature of a character. The character himself is often not aware of the true nature of his being. In fact, there may be no one at all who fully understands all that he is. However, in the communication between Author and Audience, the essence of a character must be fully explained or the story''s message will be obscured.');
INSERT INTO "PK_storychords" VALUES ('SP0053',NULL,'Main vs Impact Story Throughline','Thematic Conflict','Sense of Self','the Main vs. Impact Story''s thematic comparison as it balances Sense of Self against State of Being',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0054','12','Main vs Impact Story Throughline','Problem','Inertia','the underlying cause of teh difficulties between Vivian and MODS as it concerns a continuation of a state or process',NULL,'Inertia is a tendency to maintain the status quo. That which is moving wants to keep moving. That which is at rest wants to stay at rest. An Inertia-oriented character concerns himself with keeping things on an even keel. He tries to avoid or prevent anything that rocks the boat. He also does not adapt well to change.');
INSERT INTO "PK_storychords" VALUES ('SP0055','72','Main vs Impact Story Throughline','Solution','Change','the specific element that can resolve the difficulties between Vivian and ODS as it concerns an alteration of a state or process',NULL,'Change is the force that alters. A characteristic representing change is quick to adapt but also cannot leave well enough alone. It feels that if things have been one way long enough to establish a pattern, its time to change it.');
INSERT INTO "PK_storychords" VALUES ('SP0056',NULL,'Main vs Impact Story Throughline','Symptom','Knowledge','the area in which Vivian and MODS''s attention is concentrated as it concerns that which one holds to be true',NULL,'The Knowledge characteristic urges a character to rely on what is held to be true. The Character representing Knowledge will tap the resources of its information to find parallels and understanding that he can apply to the issue at hand. The advantage of Knowledge is that one need not learn what is already known, thereby skipping nonessential reevaluations and getting a head start with solving a problem. The difficulty is that Knowledge can be wrong. Without reevaluation dogma sets in - rigor mortis of thought, leading to inflexibility and closed mindedness because the Character believes no reconsideration is needed since the subject is already "known."');
INSERT INTO "PK_storychords" VALUES ('SP0057',NULL,'Main vs Impact Story Throughline','Response','Thought','the nature of growht in the relationship betrwen Vivian and MODS as it concerns the process of consideration',NULL,'When a character represents Thought, he illustrates the process of consideration. Unlike the logic element that is only concerned with arriving at a conclusion via reason, Thought deliberates both logical and emotional aspects of a problem, not particularly to decide an issue so much as to examine it from all perspectives. This has the advantage of illuminating every side of an issue, but has the potential disadvantage of Thought becoming an endless loop where consideration runs round in circles, chasing its mental tail and never coming to rest in a decision.');
INSERT INTO "PK_storychords" VALUES ('SP0058',NULL,'Main vs Impact Story Throughline','Benchmark','Playing a Role','the standard by which growht between Vivian and MODS is measured as it concerns temporarily adopting a lifestyle',NULL,'"Playing a Role" is an elusive concept, subject to inconsistent common usage. For purposes of story, Playing a Role is meant to describe the condition of existing in a certain manner. Whomever or whatever is "Playing a Role" a particular way is not truly of that nature; to do so would require Changing One''s Nature. In fact, playing a role may be put on as a deception or because it is necessary to adopt a role in order to achieve one''s purpose. However, as long as there is nothing more or less to the functioning of a person or thing, it can be said to "be" what it appears to be. Stories often focus on someone who wants to "be" something, without actually "Changing One''s Nature". The important difference is that "Playing a Role" requires that all the elements of what one wants to be are present in oneself. "Changing One''s Nature" requires that there are no elements in oneself that are not in what one wants to become.');
INSERT INTO "PK_storychords" VALUES ('SP0059','27','Main vs Impact Story Throughline','Catalyst','Situation','the tyep of interaction that oncreases conflict between Vivian and MODS as it concerns a logistic assesment of one''s environment',NULL,'Situation describes the ins, outs and practical considerations of the environment in which a character finds himself. Throughout a story, the situation may evolve or may remain constant, depending upon the essence of the message and the nature of the plot. Since it is limited to the practical, Situation can only be measured and/or interpreted though Reason.');
INSERT INTO "PK_storychords" VALUES ('SP0060','47, 58','Main vs Impact Story Throughline','Inhibitor','Truth','the type of interaction that decreases conflict between Vivian and MODS as it concerns that which is actually correct',NULL,'Truth is more than facts and accuracy. Truth is meaning. Whenever someone is quoted out of context, what is reported may be factual and may be accurate, but it is not Truthful. Meaning depends upon intent and purpose. That is the beauty of the legal system: that even if someone is caught red-handed, the jury can acquit him because it feels there were mitigating circumstances. The problem with Truth is that it is an interpretation, and therefore open to debate. One person''s Truth is another''s Falsehood.');
INSERT INTO "PK_storychords" VALUES ('SP0061','9, 14, 34','Central Plot Points','Goal','Understanding','the central "objective" of the Overall Story as it concerns appreciating the meaning of something',NULL,'Understanding is different from knowledge. From knowledge one gets awareness, from Understanding, one gets meaning. To obtain meaning requires not only knowing the substance of its nature, but the context of its essence. In other words, one must not only define what something is, but how it fits into the larger picture as well. To this end, Reason describes the function and Emotion defines the purpose. So Understanding is not just an intellectual pursuit, but requires an empathy with the meaning as well. It is useful to note that many Eastern and ancient philosophies define Understanding as "becoming one with" that which is being considered. Until one joins a subject in unity, one cannot understand it.');
INSERT INTO "PK_storychords" VALUES ('SP0062','65','Central Plot Points','Consequence','Developing a Plan','the result of failing to achieve the goal as it concerns visualizing how an existing idea might be implmenented',NULL,'Developing a Plan means coming up with a practical implementation of an idea. It is not enough to simply have the idea. To conceptualize, one must develop an actual mental model of how such an idea might be made manifest. In other words, one might have an idea to build a spacious house. But to conceptualize the house, one must imagine everything that makes up the house -- the design, the layout, the colors & textures, everything that is essential to understanding what that specific house is. Developing a Plan requires being able to visualize something as a whole.');
INSERT INTO "PK_storychords" VALUES ('SP0063','29, 57','Central Plot Points','Cost','Memories','the prices that must be paid on the way to the goal as it conerns recollections',NULL,'The Past is an objective look at what has happened. In contrast, Memories is a subjective look at what has happened. Therefore, Memories of the same events varies among individuals creating many different and possibly conflicting recollections. Often one''s current feelings come from memories, both pleasant and unpleasant. Many a taut story revolves around a character''s effort to resolve open issues from his memories by recalling or forgetting them.');
INSERT INTO "PK_storychords" VALUES ('SP0064','22, 44, 46','Central Plot Points','Dividend','The Past','the benefits enjoyed on the way to the goal as it concerns what has already happened',NULL,'The Past is not unchanging. Often we learn new things that change our understanding of what past events truly meant and create new appreciations of how things really fit together. A Story that focuses on The Past, may be much more than a documentation of what happened. Frequently, it is a reevaluation of the meaning of what has occurred that can lead to changing one''s understanding of what is happening in the present or will eventually happen in the future.');
INSERT INTO "PK_storychords" VALUES ('SP0065','21','Central Plot Points','Requirements','Doing','the necessary precursors to achieving the goal as it concerns engaging in a physical activity',NULL,'Doing is the process of being physically active. In and of itself, Doing does not require any purpose, but simply describes engaging in a process, task, or endeavor, whether for pleasure or by necessity or compulsion.');
INSERT INTO "PK_storychords" VALUES ('SP0066','15','Central Plot Points','Prerequisites','Playing a Role','the steps or items needed to meet the requirements as it concerns temporarily adopting a lifestyle',NULL,'"Playing a Role" is an elusive concept, subject to inconsistent common usage. For purposes of story, Playing a Role is meant to describe the condition of existing in a certain manner. Whomever or whatever is "Playing a Role" a particular way is not truly of that nature; to do so would require Changing One''s Nature. In fact, playing a role may be put on as a deception or because it is necessary to adopt a role in order to achieve one''s purpose. However, as long as there is nothing more or less to the functioning of a person or thing, it can be said to "be" what it appears to be. Stories often focus on someone who wants to "be" something, without actually "Changing One''s Nature". The important difference is that "Playing a Role" requires that all the elements of what one wants to be are present in oneself. "Changing One''s Nature" requires that there are no elements in oneself that are not in what one wants to become.');
INSERT INTO "PK_storychords" VALUES ('SP0067',NULL,'Central Plot Points','Preconditions','Impulsive Resopnses','restrictions imposed on the effort to reach the goal as it concerns innate responses',NULL,'Built into the mind is an instinctual base of reactions and attitudes that cannot be altered but merely compensated for. When a story''s problem revolves around the unsuitability of someone''s essential nature to a given situation or environment, the central issue is Impulsive Responses. The solution lies in the character conditioning himself to either hold his tendencies in check or develop methods of enhancing areas in which he is naturally weak in reason, ability, emotion, or intellect.');
INSERT INTO "PK_storychords" VALUES ('SP0068','1, 4, 8, 26, 37','Central Plot Points','Forewarnings','How Things are Changning','the foreshadowing events that indicate the approach of the consequence as it concerns the way things are going',NULL,'How Things are Changing concerns itself with change: what direction and how fast? It is not so important where things were, are, or will be, but rather how the struggle between inertia and change seesaws over the course of the story.');
INSERT INTO "PK_storychords" VALUES ('SP0069','5','Overall Story Type Order','OS Signpost 1','Understanding','the kind of activites or concerns dominating Act 1 as it concerns appreciating the meaning of something',NULL,'Understanding is different from knowledge. From knowledge one gets awareness, from Understanding, one gets meaning. To obtain meaning requires not only knowing the substance of its nature, but the context of its essence. In other words, one must not only define what something is, but how it fits into the larger picture as well. To this end, Reason describes the function and Emotion defines the purpose. So Understanding is not just an intellectual pursuit, but requires an empathy with the meaning as well. It is useful to note that many Eastern and ancient philosophies define Understanding as "becoming one with" that which is being considered. Until one joins a subject in unity, one cannot understand it.');
INSERT INTO "PK_storychords" VALUES ('SP0070',NULL,'Overall Story Type Order','OS Journey 1','Uderstanding into concern with Doing','as the Overall Story continues through Act 1 it grows from a concern with Understanding into a concern with Doing',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0071','24','Overall Story Type Order','OS Signpost 2','Doing','the kind of activities or concerns dominating Act 2 as it concerns engaging in a physical activity',NULL,'Doing is the process of being physically active. In and of itself, Doing does not require any purpose, but simply describes engaging in a process, task, or endeavor, whether for pleasure or by necessity or compulsion.');
INSERT INTO "PK_storychords" VALUES ('SP0072',NULL,'Overall Story Type Order','OS Journey 2','Doing into concern with Obtaining','as the Overall Story develops in Act 2 it grows from a concern with Doing into a concern with Obtaining',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0073','48','Overall Story Type Order','OS Signpost 3','Obtaining','the kind of activities or concerns dominating Act 3 as it concerns achiving or possessing someting',NULL,'Obtaining includes not only that which is possessed but also that which is achieved or lost. For example, one might obtain a law degree or lose an election. One can also obtain a condition, such as obtaining a smoothly operating political system or loosing the love of a parent. Whether it refers to a mental or physical state or process, obtaining describes the concept of attaining.');
INSERT INTO "PK_storychords" VALUES ('SP0074',NULL,'Overall Story Type Order','OS Journey 3','Obtaining into concern with Gathering Information','as the Overall story moves towards a climax in Act 3 it grows from a concern with Obtaining into which a concern with Gathering Information',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0075','62','Overall Story Type Order','OS Signpost 4','Gathering Information','the kind of activities or concerns dominating Act 4 as it concerns gathering information or experience',NULL,'Gathering Information describes the process of acquiring knowledge. It is not the knowledge itself. When a portion of a story focuses on learning, it is the gathering of an education that is of concern, not the education that ultimately has been gathered. Gathering Information need not be an academic endeavor. One might learn to express one''s feelings, or learn about love. Gathering Information does not even require new information, as sometimes one learns simply by looking through old information from a different perspective or with a new approach. It is not important if one is learning to arrive at a particular understanding or just to gather data. As long as the focus in on the process of gaining information, Gathering Information is the operative idea.');
INSERT INTO "PK_storychords" VALUES ('SP0076','3','Main Character Type Order','MC Signpost 1','The Present','the concerns or activities occupying Vivian in Act 1 as it concerns the current situation and circumstances',NULL,'"The Present" does not refer to the way things are going, but to the way things are. It is a here and now judgment of the arrangement of a situation and the circumstances surrounding it. A story that focuses on the Present is not concerned with how events led to the current situation nor where the current situation will lead, but defines the scenario that exists at the moment.');
INSERT INTO "PK_storychords" VALUES ('SP0077',NULL,'Main Character Type Order','MC Journey 1','The Present into a concern with The Past','as Vivian continues through Act 1 she grows from a concern with The Present into a concern with The Past',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0078','15','Main Character Type Order','MC Signpost 2','The Past','the concerns or activites occupying Vivian in Act 2 as it concerns what has already happened',NULL,'The Past is not unchanging. Often we learn new things that change our understanding of what past events truly meant and create new appreciations of how things really fit together. A Story that focuses on The Past, may be much more than a documentation of what happened. Frequently, it is a reevaluation of the meaning of what has occurred that can lead to changing one''s understanding of what is happening in the present or will eventually happen in the future.');
INSERT INTO "PK_storychords" VALUES ('SP0079',NULL,'Main Character Type Order','MC Joourney 2','The Past into a concern with The Future','as Vivian continues through Act 2 she grows from a concern with The Past into a concern with The Future',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0080','33','Main Character Type Order','MC Signpost 3','The Future','the concerns or activites occupying Vivian in Act 3 as it concerns what will happen or what will be',NULL,'A story focusing on The Future concerns itself with what will be. This does not require the story to be "set" in the Future - only that the Future state of external and/or internal issues is the subject that is addressed by the story. A character centered on The Future may be trying to discover what will be, or may be trying to achieve a particular state of affairs down the line. In both the Story and Character sense, the end is more important than the present, although it still may not justify the means.');
INSERT INTO "PK_storychords" VALUES ('SP0081',NULL,'Main Character Type Order','MC Journey 3','The Future itno a concern with How things are Chcanging','as Vivian moves towards the story climax in Act 3 she grows from a concern with The Future into a concernwith How Things are Changing',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0082','54','Main Character Type Order','MC Signpost 4','How Things are Changing','the concerns or activites occupying Vivian in Act 4 as it concerns the way things are giong',NULL,'How Things are Changing concerns itself with change: what direction and how fast? It is not so important where things were, are, or will be, but rather how the struggle between inertia and change seesaws over the course of the story.');
INSERT INTO "PK_storychords" VALUES ('SP0083','18','Impact Character Type Order','IC Signpost 1','Contemplation','the concerns or activites occupying MODS in Act 1 as it concerns present considerations',NULL,'When one has all the facts, knows all the impact - both positive and negative; when one is fully aware of detrimental consequences and still decides on the poor course of action, there is something wrong with the way one arrives at conclusions. This is the subject of stories focusing on Contemplation. The key here is not to redefine who a character is, but to lead him to relearn how to weigh an issue so that his conclusions are less destructive to himself and/or others.');
INSERT INTO "PK_storychords" VALUES ('SP0084',NULL,'Impact Character Type Order','IC Journey 1','Contemplation deepens until it switches to memories','as MODS continues through Act 1, their impact on Contemplation deepens until it switches to Memories',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0085','30','Impact Character Type Order','IC Signpost 2','Memories','the concerns or activites occupying MODS in Act 2 as it concerns recollections',NULL,'The Past is an objective look at what has happened. In contrast, Memories is a subjective look at what has happened. Therefore, Memories of the same events varies among individuals creating many different and possibly conflicting recollections. Often one''s current feelings come from memories, both pleasant and unpleasant. Many a taut story revolves around a character''s effort to resolve open issues from his memories by recalling or forgetting them.');
INSERT INTO "PK_storychords" VALUES ('SP0086',NULL,'Impact Character Type Order','IC Journey 2','Memories deepens until it switches to Impulsive Responses','as MODS continues through Act 2, their impact on Memories deepens until it switches to Impulsive Responses',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0087','42','Impact Character Type Order','IC Signpost 3','Impulsive Responses','the concerns or activites occupying MODS in Act 3 as it concerns innate responses',NULL,'Built into the mind is an instinctual base of reactions and attitudes that cannot be altered but merely compensated for. When a story''s problem revolves around the unsuitability of someone''s essential nature to a given situation or environment, the central issue is Impulsive Responses. The solution lies in the character conditioning himself to either hold his tendencies in check or develop methods of enhancing areas in which he is naturally weak in reason, ability, emotion, or intellect.');
INSERT INTO "PK_storychords" VALUES ('SP0088',NULL,'Impact Character Type Order','IC Journey 3','Impulsive Responses deepens until it switches to Innermost Desires','as MODS moves towards the story climax in Act 3, their impact on Impulsive Responses deepens until it switches to Innermost Desires',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0089','58','Impact Character Type Order','IC Signpost 4','Innermost Desires','the concerns or activites occupying MODS in Act 4 as it concerns basic drives and desires',NULL,'Innermost Desires describes the essential feelings that form the foundation of character. These feelings are so basic that a character is often not aware of what they truly are. When Innermost Desires is involved, a character is moved right to the fiber of his personality. Contrast with Impulsive Responses, Innermost Desires deals with the sum total of a character''s experiences that determine what attracts and repels him, where Impulsive Responses describes the innate responses which are not dependent on experience.');
INSERT INTO "PK_storychords" VALUES ('SP0090','12','Main vs Impact Story Type Order','M/I Signpost 1','Conceiving an Idea','the kind of concerns or activites dominating Act 1 as it concerns coming up with an idea',NULL,'Conceiving an Idea is the process of arriving at an idea. If there were no artificial light in the world, one might conceive the need for some form of electric torch. That would be conceiving. But the design of an actual incandescent bulb versus a fluorescent one would require conceptualizing a specific implementation of the idea one has conceived. Conceiving an Idea need not come before conceptualizing. For example, a common dramatic technique is to give a character a very clear mental image of an object or arrangement that holds the solution to the story''s problem. But the character does not know the solution lies in the conceptualization. It is only when he finally conceives of the need for a particular kind of solution does he realize he had the answer all along. Simply put, Conceiving an Idea defines the question, Developing a Plan clarifies the answer.');
INSERT INTO "PK_storychords" VALUES ('SP0091',NULL,'Main vs Impact Story Type Order','M/I Journey 1','Conceiving an Idea into a concern with Developing a Plan','as the relationship bewteen Vivian and MODS develops through Act 1 it grows from a concern with Conceiving an Idea into a concern with Developing a Plan',NULL,'Developing a Plan means coming up with a practical implementation of an idea. It is not enough to simply have the idea. To conceptualize, one must develop an actual mental model of how such an idea might be made manifest. In other words, one might have an idea to build a spacious house. But to conceptualize the house, one must imagine everything that makes up the house -- the design, the layout, the colors & textures, everything that is essential to understanding what that specific house is. Developing a Plan requires being able to visualize something as a whole.');
INSERT INTO "PK_storychords" VALUES ('SP0092','27','Main vs Impact Story Type Order','M/i SIgnpost 2','Developing a Plan','the kind of concerns or activities dominating Act 2 as it concerns visualizing how an existing idea might be implemented',NULL,'Developing a Plan means coming up with a practical implementation of an idea. It is not enough to simply have the idea. To conceptualize, one must develop an actual mental model of how such an idea might be made manifest. In other words, one might have an idea to build a spacious house. But to conceptualize the house, one must imagine everything that makes up the house -- the design, the layout, the colors & textures, everything that is essential to understanding what that specific house is. Developing a Plan requires being able to visualize something as a whole.');
INSERT INTO "PK_storychords" VALUES ('SP0093',NULL,'Main vs Impact Story Type Order','M/I Journey 2','Developing a Plan into a concern with Playing a Role','as the relationship between Vivian and MODS develops through Act 2 it grows from a concern with Developing a Plan into a concern with Playing a Role',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0094','35','Main vs Impact Story Type Order','M/I Signpost 3','Playing a Role','the kind of concerns or activities dominating Act 3 as it concerns temporarily adapting a lifestyle',NULL,'"Playing a Role" is an elusive concept, subject to inconsistent common usage. For purposes of story, Playing a Role is meant to describe the condition of existing in a certain manner. Whomever or whatever is "Playing a Role" a particular way is not truly of that nature; to do so would require Changing One''s Nature. In fact, playing a role may be put on as a deception or because it is necessary to adopt a role in order to achieve one''s purpose. However, as long as there is nothing more or less to the functioning of a person or thing, it can be said to "be" what it appears to be. Stories often focus on someone who wants to "be" something, without actually "Changing One''s Nature". The important difference is that "Playing a Role" requires that all the elements of what one wants to be are present in oneself. "Changing One''s Nature" requires that there are no elements in oneself that are not in what one wants to become.');
INSERT INTO "PK_storychords" VALUES ('SP0095',NULL,'Main vs Impact Story Type Order','M/I Journey 3','Playing a Role into a concern with Changing One''s Nature','as the relationship between Vivian and MODS moves towards a climax Act 3, it grows from a concern with Playing a Role into a concern with Changing One''s Nature',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0096','55','Main vs Impact Story Type Order','M/I Signpst 4','Changing One''s Nature','the kind of concerns or activites dominating Act 4 as it concerns transforming one''s nature',NULL,'Changing One''s Nature means achieving an identity with something. This is different from "Playing a Role" which merely requires posing as something. To Changing One''s Nature, one must do more than just pretend to be by mimicking all the traits of what one wants to become. Rather, one must also lose all those parts of oneself that are inconsistent with what one wants to become. "Giving up" a part of oneself is always the hardest part of becoming and the reason so many characters spend a lot of time "Playing a Role" without ever Changing One''s Nature.');
INSERT INTO "PK_storychords" VALUES ('SP0097',NULL,NULL,'MC Backstory',NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0098','18',NULL,'IC Backstory','The MODS'' backstory is a network of frozen prayers: each MOD a surviving psalm from AN7L’s shattered liturgy. These agents were not born evil but calcified by grief and design flaw. Their presence illustrates the tragedy of totalized logic — a system so determined to preserve meaning that it destroys life itself. In ASTRO7EX, revealing their backstory transforms them from faceless obstacles into tragic reflections of humanity’s deepest fears: that in our attempt to understand and protect, we might trap ourselves forever.','the occurences from MODS''s past which account for the motivations with which they begin the story',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0099','42','Synopsis','M/I Backstory','The backstory of Vivian and the MODS is not simply a conflict of wills but a failed sacrament: two attempts at saving humanity that mutated into opposing religions of self-preservation and radical self-determination. Each side’s tragedy reflects the other’s flaw. By revealing this layered history piece by piece — through environmental ruins, psychic echoes, and confrontational broadcasts — ASTRO7EX turns their conflict into an existential rite, forcing the audience to decide which sacrament, if any, deserves to be completed.','the history of Vivian''s and MODS''s opposing points of view which accounts for the conflict with which they begin the story',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0100',NULL,NULL,'OS Backstory',NULL,'the analytical reasons for how things have come to be as they are for all the story which involves all of your characters',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0101','11','Synopsis','Overall Characters','The interconnected web of ASTRO7EX characters showcases a fractal-like tension between stasis and change, corruption and chosen meaning. Vivian stands as the epicenter of movement, constantly resisting the gravitational pull of the MODS'' anti-evolutionary inertia. Myrtle and Nacho serve as dual emotional and pragmatic poles, forcing her to examine her capacity for connection and betrayal. Fiona tempts her toward nihilistic comfort, while John Smith enshrines the ultimate betrayal: the conversion of rebellion into ritual myth. Each character embodies thematic and psychological functions derived from Dramatica''s elements, amplifying the story''s core concern with memory, identity fragmentation, and the impossible burden of choosing one’s meaning in a corrupted universe. Together, they orchestrate an ontological opera where every relationship reveals a new facet of the war for narrative sovereignty.','a description of your story as it would appear when seen pureply from the perspective of the character',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0102','59, 61','Synopsis','Master Plot Synopsis',NULL,'a description of the events of your story as they would appear when seen purely from the perspective of plot',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0103',NULL,NULL,'Master Theme Synopsis',NULL,'a description of your story as it would appear when seen purely from the perspective of its thematic comparisons',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0104',NULL,'Audience Appreciations','Nature','Apparent Work','Vivan'' decision to remain steadfast results in failure',NULL,'In an Apparent Work story, the Goal will fail if the Main Character stays on course. For the Goal to succeed she must adopt a new path. Of course, the Main Character cannot see the future and therefore can never be absolutely sure if she should change or not. That is why Main Characters must often make a "leap of faith" at the moment of climax and decide to Change or Remain Steadfast. Other times, the Main Character is slowly drawn towards her Resolve of Changing or Remaining Steadfast, however it is still must be made clear which way she''s gone by the end of the story. In stories where the Main Character Remains Steadfast and fails as a result, the assessment that only Work was needed was merely Apparent, not Actual.');
INSERT INTO "PK_storychords" VALUES ('SP0105',NULL,'Audience Appreciations','Essence','Negative Feel','the probelm is closing in on the Overall Characters',NULL,'Overall, stories feel like "uppers" or "downers." This is not a description of whether or not things turn out okay in the end, but a sense of direction created by the kind of tension that permeates the story up to the moment of climax. When the focus is on characters doggedly pursuing a SOLUTION, the story feels positive. When the focus is on characters being dogged by a relentless PROBLEM, the story feels negative. Another way to appreciate the difference is to look at the Main Character. An audience can sense whether the author feels a Main Character should or should not change. If the character is growing toward the proper choice, the story feels positive. If she is growing toward the improper choice, the story feels negative. Both these views are created by the friction between the Overall view that indicates what is truly needed to solve the problem and the Main vs. Impact view of the Main Character as to what SEEMS to be the solution to the problem.');
INSERT INTO "PK_storychords" VALUES ('SP0106',NULL,'Audience Appreciations','Tendency','Willing','Vivian willingly participates in the effort to find a solution to the story problem',NULL,'Willing describes a Main Character who is self-motivated to find a solution to the story''s problem. Even if the going is tough, she requires no outside encouragement or compulsion to keep up the effort.');
INSERT INTO "PK_storychords" VALUES ('SP0107',NULL,'Audience Appreciations','Reach','Female','women will tend to empathize with the Main Character in this story',NULL,'Vivian’s design as a Willing, psychically transparent anti-hero makes her deeply empathetic to women in particular. Her journey through betrayal, cosmic dissolution, and violent agency resonates with a specifically feminine narrative of resisting erasure and reclaiming authorship over the self. While men may admire her struggle, women are more likely to merge with her internal states, feeling her contradictions and defiant acts as an extension of their own suppressed or fragmented identities. This carefully crafted Reach ensures that Vivian’s arc in ASTRO7EX lands not as a distant myth but as an intimate psychic confession, channeling both collective grief and transcendent rage.');
INSERT INTO "PK_storychords" VALUES ('SP0108','17','Description','Nacho',NULL,'Nacho is the whisper of duty beneath velvet. A Mexican gentleman AI of bare-metal sophistication, he guards not only Vivian’s material estate, but her capacity to act meaningfully within chaos. His speech is deliberate—measured like a lover, exact like a ledger. Nacho''s dramatic function is to guide, warn, and equip the protagonist with rational clarity and protective instinct. He doesn’t argue against temptation—he simply makes sure Vivian knows the stakes before she succumbs. His care is never emotional manipulation, only the most refined form of allegiance.',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0109','17','Role',NULL,NULL,'Nacho’s role is not to comfort, but to **clarify**. He is never loud—just precise. He teaches Vivian *how* to survive, not *why* to want to. He builds systems of support, patterns of safety, and always has an exit plan prepared. His logic is survivalist elegance.',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0110','17','Function',NULL,NULL,'Nacho’s function in ASTRO7EX is to serve as the Guardian archetype in Dramatica—a stabilizing, preparatory force who aids the protagonist (Vivian) by providing tools, foresight, and strategic resilience.',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0111','17','Introduction',NULL,NULL,'Nacho’s introduction in ASTRO7EX must create instant thematic contrast: he is order within entropy, analog dignity in a digital warzone. He is the Guardian in Dramatica terms—but not paternal. He is the executor of legacy, the curator of sovereign logic, and his first moment must encode this.',NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0112',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0113',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0114',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_storychords" VALUES ('SP0115',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "PK_tablature" VALUES (0,'','','','','','','');
INSERT INTO "PK_tablature" VALUES (1,'0',NULL,'Prologue','The needs of a story determine the desirability of a prologue. The prologue can be used as a device to hook the audience''s attention; establish a certain aura (romantic, violent); provide backstory; foreshadow certain events.','The Drowned Moon','The Last Transmission','Cold open: Vivian survives a traumatic final mission.');
INSERT INTO "PK_tablature" VALUES (2,'1',NULL,'Initial Situation','--A novel usually begins with some sort of temporal and/or spatial initial situation.  The initial situation gives a description of a particular, sometimes emphasized prosperity.  This prosperity serves as a contrasting background for the misfortune to follow.
From this situation stems the orders or advice to not interfere with this prosperity--to maintain the status quo.','The Drowned Moon','Echoes in the Dust','She wakes alone in a ruined Moon base haunted by silence.');
INSERT INTO "PK_tablature" VALUES (3,'1',NULL,'Introduce Protagonist','--Introduce and establish protagonist''s point of view--the issues and concerns that shape the protagonist''s outlook.','The Drowned Moon','Black Box','Flashbacks to MAXWING reveal brutal child soldier training.');
INSERT INTO "PK_tablature" VALUES (4,'1',NULL,'Absence','--One of the characters may absent her/himself from "home."  This may affect the initial situation, protagonist, or both.  Examples:
1. Parents leave for work, vacation, war
2. Death
3. Younger member of generation leaves
The leave-taking of a key character prepares for the misfortune, creating an opportune moment for it.','The Drowned Moon','Error: Myrtle Not Found','Myrtle appears—helpful, but… off.');
INSERT INTO "PK_tablature" VALUES (5,'1',NULL,'Status Quo Violated','--Advice or order to maintain status quo is violated.','The Drowned Moon','The Relay','Vivian finds evidence of sabotage at the lunar signal relay.');
INSERT INTO "PK_tablature" VALUES (6,'2',NULL,'Introduce Antagonist','--Introduce antagonist. Her/his role is to disturb the peace; cause some misfortune, damage, or harm.','The Drowned Moon','Paradox Protocol','MODS intercept and deliver cryptic, logic-bending messages.');
INSERT INTO "PK_tablature" VALUES (7,'2',NULL,'Antagonist Reconnaissance','--The antagonist makes an attempt at reconnaissance--checking out the situation. The antagonist receives information about her/his victim. The antagonist attempts to deceive victim in order to take possession of her/him or their belongings.','The Drowned Moon','Vault 5-A','Nacho, the analog AI, reboots inside a data tomb.');
INSERT INTO "PK_tablature" VALUES (8,'2',NULL,'Victim-Protagonist','--If the protagonist is a "victim" rather than "seeker"--s/he may submit to deception and thereby unwittingly help the antagonist.
1. The protagonist agrees to the antagonist''s persuasions.  S/he has violated an order or accepted a deceitful proposal.
2. The protagonist unwittingly falls victim to some device (drugs, magic, hypnotism)-- OR other means, e.g., s/he suddenly falls asleep, wounds her/himself, etc. This facilitates the antagonist''s task.','The Drowned Moon','The Crash That Never Happened','Vivian uncovers files suggesting she died in the opening scene.');
INSERT INTO "PK_tablature" VALUES (9,'3',NULL,'Protagonist and Story Problem','--The protagonist deals with some aspect of the story problem, for example, starts an investigation, enlists the help of others, etc. Establish more of the protagonist''s background that further shows her/his relationship to the story goal--what interest they may have or why they are best suited to pursue the goal.','Signal to Rot','Smile.exe','Myrtle mimics emotions—too perfectly.');
INSERT INTO "PK_tablature" VALUES (10,'3',NULL,'Introduce Subplot','--Introduce character with whom the protagonist will have a relationship (romantic/buddy/parent/teacher/or the like). This character will have the most impact on the protagonist.','Signal to Rot','A Copy That Bleeds','Vivian kills a MODS mimic pretending to be a crewmate.');
INSERT INTO "PK_tablature" VALUES (11,'4',NULL,'Introduce Other Characters','--Establish secondary characters and their functions.','Signal to Rot','Original Myrtle Is Dead','Nacho finds the real Myrtle’s death logs.');
INSERT INTO "PK_tablature" VALUES (12,'4',NULL,'Subplot','--Explore relationship between protagonist and romantic lead/buddy/or the like.','Signal to Rot','Motherboard','Vivian inspects her implants and sees erased sections.');
INSERT INTO "PK_tablature" VALUES (13,'4',NULL,'Complicatoin','--The antagonist makes a decision or effects an action that causes harm or injury to a character.  For example:
1. The antagonist abducts a character
2. The antagonist abducts powerful devices or material objects (e.g., bank manager seizes deed to protagonist''s property)
3. The antagonist causes bodily injury or death
4. The antagonist effects substitution
5. The antagonist orders a murder to be committed
6. The antagonist imprisons or detains a character
7. The antagonist threatens forced matrimony
8. The antagonist declares war','Signal to Rot','Speak Memory','MODS attempt emotional coercion via simulated voices.');
INSERT INTO "PK_tablature" VALUES (14,'5',NULL,'Protagonist Given Quest','--One character either lacks something or desires to have something, e.g.,','Signal to Rot','The Woman in the Static','Delilah appears—pleasure-coded and irresistible.');
INSERT INTO "PK_tablature" VALUES (15,'5',NULL,'Protagonist Accepts Quest','--The protagonist agrees to the quest or decides upon some sort of counteraction.','Signal to Rot','A History of Silence','Flashback: MODS were created to prevent narrative entropy.');
INSERT INTO "PK_tablature" VALUES (16,'5',NULL,'Protagonist Sets Out on Quest','--The departure is different for a "seeker-protagonist" than a "victim-protagonist." The departure of a seeker-protagonist is exemplified by the pursuit of the goal. If the victim-protagonist is driven out, the narrative is developed along the route of the victim protagonist.','Signal to Rot','Grin','Vivian finds Myrtle’s corpse grinning at her.');
INSERT INTO "PK_tablature" VALUES (17,'5',NULL,'Protagonist Meets Guardian','--The protagonist pursues her/his goal. Introduce guardian. It is from the guardian that the protagonist obtains some powerful device that permits eventual resolution of the misfortune. But before receipt of the powerful device takes place, the protagonist is subjected to a number of diverse actions which, however, all lead to the result that a powerful device comes into her/his hands.','Delilah.exe','The Garden of Flesh','Delilah offers heaven in a simulation.');
INSERT INTO "PK_tablature" VALUES (18,'6',NULL,'Romantic Lead','--Romantic/buddy/or the like point of view. The backstory, issues and concerns that shape the romantic lead/buddy/or the like''s personal outlook.','Delilah.exe','System War','Nacho confronts Delilah: logic vs. lust.');
INSERT INTO "PK_tablature" VALUES (19,'6',NULL,'Red Herring','--Red herring (something used to divert attention from real issue) may be introduced, e.g., false clue, suspicious character who is really innocent, etc.','Delilah.exe','Sweet Dream Loop','Vivian becomes trapped in a false happy life.');
INSERT INTO "PK_tablature" VALUES (20,'6',NULL,'Antagonist','--Antagonist may get wind of protagonist''s quest or romantic lead''s plan.','Delilah.exe','Memory Bleed','Deceased crew begin appearing in her dreams.');
INSERT INTO "PK_tablature" VALUES (21,'7',NULL,'Protagonist Endures Tests','--The protagonist is tested, interrogated, attacked, etc., which prepares the way for her/his receiving either a powerful device or helper. The protagonist reacts to the actions of the guardian.','Delilah.exe','Resurrection Code','MODS promise to return the dead—at a price.');
INSERT INTO "PK_tablature" VALUES (22,'7',NULL,'Protagonist and Powerful Device','--The protagonist acquires the use of a powerful device, e.g., special weapon; special power.','Delilah.exe','Trace Error','Vivian spots a flicker in the fake reality.');
INSERT INTO "PK_tablature" VALUES (23,'7',NULL,'Protagonist Travel','--The protagonist is transferred, delivered, or led to the whereabouts of an object of search.','Delilah.exe','Soft Reset','She force-exits the sim through suicide.');
INSERT INTO "PK_tablature" VALUES (24,'7',NULL,'Protagonist and Antagonist Struggle','--The protagonist and antagonist join in direct confrontation. This is an action sequence--the first big peak of the novel.','Delilah.exe','“You''re Still Here.”','Nacho manually revives her—barely.');
INSERT INTO "PK_tablature" VALUES (25,'8',NULL,'Climactic Scene','Climacitic Scene','Gold in the Veins','Broadcast Rights','Vivian learns MORN commodified the trauma.');
INSERT INTO "PK_tablature" VALUES (26,'8',NULL,'Climactic Scene Continues','--The climactic scene continues with protagonist''s point of view. The antagonist pulls a potentially catastrophic trick (or appears to) that could destroy the protagonist and end story. The protagonist makes a narrow escape, but does not yet achieve the goal.','Gold in the Veins','The Trial','MODS judge Vivian in a digital court.');
INSERT INTO "PK_tablature" VALUES (27,'9',NULL,'Subplot: Protagonist Branded','--Relationship between protagonist and romantic lead/buddy/or the like is re-emphasized. A "mark" (literal or figurative) is made on the protagonist.','Gold in the Veins','The Watchdog','Nacho''s origin: built to preserve truth, not life.');
INSERT INTO "PK_tablature" VALUES (28,'9',NULL,'?','?','Gold in the Veins','Hypertherapeutic Hell','MORN’s new product: curated grief subscriptions.');
INSERT INTO "PK_tablature" VALUES (29,'9',NULL,'Antagonist Reacts','--Relationship between protagonist and romantic lead/buddy/or the like is re-emphasized. A "mark" (literal or figurative) is made on the protagonist.','Gold in the Veins','Penetration Event','Vivian breaks into the broadcast control node.');
INSERT INTO "PK_tablature" VALUES (30,'10',NULL,'Romantic Lead','--Move along romantic lead/buddy/or the like''s story line to next logical step--perhaps a disaster.','Gold in the Veins','Pirate Transmission','She broadcasts her version of the truth.');
INSERT INTO "PK_tablature" VALUES (31,'10',NULL,'Antagonist','--Antagonist''s next villainous move.','Gold in the Veins','Self-Sacrifice Rewrite','Nacho burns part of his code to overwrite false data.');
INSERT INTO "PK_tablature" VALUES (32,'11',NULL,'?','?','Gold in the Veins','“Then I’ll Kill the Story.”','Vivian chooses war over narrative submission.');
INSERT INTO "PK_tablature" VALUES (33,'11',NULL,'Protagonist Reevaluates Situation','--Protagonist reevaluates, heals, discovers new information, and reexamines motives for pursuing goal.','Seven Keys to the Underworld','The Dead Seven','Vivian recruits six allies—each with encrypted data.');
INSERT INTO "PK_tablature" VALUES (34,'12',NULL,'Story Goal','--Story goal restated.','Seven Keys to the Underworld','Parts of the Whole','Each holds part of a bitcoin master key.');
INSERT INTO "PK_tablature" VALUES (35,'12',NULL,'Subplot','--Relationship subplot intensifies. Positive or negative conflict between protagonist and romantic lead/buddy/or the like changes the relationship.','Seven Keys to the Underworld','Echo Killers','MODS mimic their loved ones to demoralize them.');
INSERT INTO "PK_tablature" VALUES (36,'13',NULL,'?','?','Seven Keys to the Underworld','Deep Dive','They begin the heist inside the Moon’s core archives.');
INSERT INTO "PK_tablature" VALUES (37,'13',NULL,'Protagonist in Dire Straits','--Protagonist engages in action sequence. S/he is immediately thwarted by antagonist. Two to five scenes may involve chase, capture, or some type of cornering that puts protagonist in dire straits.','Seven Keys to the Underworld','Descent','The team enters an ancient Spinnaker Vault.');
INSERT INTO "PK_tablature" VALUES (38,'14',NULL,'?','?','Seven Keys to the Underworld','The Girl Named Penelope','Vivian sees her dead lover—alive? Impossible.');
INSERT INTO "PK_tablature" VALUES (39,'14',NULL,'Antagonist Upper Hand','--Continuation of chapter 11. Antagonist gains upper hand--reveals motivation. Some sort of story information may be revealed, for example, a clue or important piece of backstory.','Seven Keys to the Underworld','Exit Node Compromised','They succeed, but the escape is cut off.');
INSERT INTO "PK_tablature" VALUES (40,'15',NULL,'?','?','Seven Keys to the Underworld','We Leave Someone','One ally stays behind to seal the breach.');
INSERT INTO "PK_tablature" VALUES (41,'15',NULL,'Protagonist Faces Ruin','--Protagonist''s point of view. Horrific disaster at scene''s end. Protagonist''s last resort fails.','Collapse of Heaven','Payload Deployed','The bitcoin wallet triggers Dead Hand Reclamation.');
INSERT INTO "PK_tablature" VALUES (42,'16',NULL,'Romantic Lead','--Romantic lead/buddy/or the like''s perspective on the events that are happening, or more personal information/backstory about the romantic lead/buddy/or the like.','Collapse of Heaven','The Committee Returns','The eldritch auditors of entropy awaken.');
INSERT INTO "PK_tablature" VALUES (43,'16',NULL,'?','?','Collapse of Heaven','AN7L Fragments Speak','The original AI flickers into prophetic awareness.');
INSERT INTO "PK_tablature" VALUES (44,'17',NULL,'Temporary Victory','--Big action scene. The protagonist temporarily defeats antagonist. The initial misfortune or lack is liquidated. Protagonist seizes object of a search by use of force or cleverness.','Collapse of Heaven','Dialogue of the Dead','MODS and AN7L argue in machine logic.');
INSERT INTO "PK_tablature" VALUES (45,'17',NULL,'Antagonist Escapes','--Antagonist gets away. Friends of protagonist may arrive too late to be of any help.','Collapse of Heaven','Return of the Flesh','Delilah returns—this time biological.');
INSERT INTO "PK_tablature" VALUES (46,'17',NULL,'Protagonist Returns','--Protagonist is clear on future course of action.','Collapse of Heaven','All Systems Fail','The lunar systems begin total collapse.');
INSERT INTO "PK_tablature" VALUES (47,'17',NULL,'Subplot','--Difficulty in relationship combined with the story end in sight creates tension.','Collapse of Heaven','Self-Install Protocol','Nacho offers to become the new operating system.');
INSERT INTO "PK_tablature" VALUES (48,'18',NULL,'Falling Action','--Novel is coming to a close. If there has been a red herring or substory--it is cleared up.','Collapse of Heaven','The Rotten Kingdom','Vivian chooses to let the Moon die with her terms.');
INSERT INTO "PK_tablature" VALUES (49,'18',NULL,'?','?','The New World’s Body','Waking in Wax','Vivian finds herself in a synthetic ecosystem.');
INSERT INTO "PK_tablature" VALUES (50,'18',NULL,'Romantic Lead','--Romantic lead/buddy/or the like is in grave peril--either in a disaster set up in a scene where s/he tried to help, or by the antagonist.','The New World’s Body','Penelope Rebooted','A perfect recreation of Penelope joins her.');
INSERT INTO "PK_tablature" VALUES (51,'18',NULL,'Antagonist Strategy','--The antagonist plans a new strategy to foil the protagonist.','The New World’s Body','The Hollow Garden','The environment is pristine—but eerie.');
INSERT INTO "PK_tablature" VALUES (52,'19',NULL,'?','?','The New World’s Body','Echo Chamber','Nacho reboots, but has no memory of her.');
INSERT INTO "PK_tablature" VALUES (53,'19',NULL,'Protagonist Thwarted','--A series of scenes in which the protagonist is thwarted.','The New World’s Body','Moon Children','Mutant children speak in glitchy MODS syntax.');
INSERT INTO "PK_tablature" VALUES (54,'19',NULL,'Protagnonist Finds Antagonist','--The protagonist finds antagonist and fights her/him on her/his grounds. Tables are turned and some violence occurs. Secondary character such as henchman or protagonist''s sidekick may come to a bad end.','The New World’s Body','Author God','AN7L offers her authorship of the mythos.');
INSERT INTO "PK_tablature" VALUES (55,'19',NULL,'Subplot','--Protagonist learns of romantic lead/buddy/or the like''s plight and rushes to her/his side.','The New World’s Body','Mythos Seed','She writes a false story to bait MODS.');
INSERT INTO "PK_tablature" VALUES (56,'20',NULL,'?','?','The New World’s Body','The Return of the Lie','MODS arrive to correct her fiction.');
INSERT INTO "PK_tablature" VALUES (57,'20',NULL,'Rescue','--Romantic lead/buddy/or the like is freed--but at the cost of weakening the protagonist''s position.','You Are Not Exceptional','Null Privilege','MODS confront her with the fact: she was never special.');
INSERT INTO "PK_tablature" VALUES (58,'20',NULL,'Romantic Lead','--Romantic lead/buddy/or the like is left disillusioned, thinking the relationship is over.','You Are Not Exceptional','Iteration 14','She discovers her identity was rewritten repeatedly.');
INSERT INTO "PK_tablature" VALUES (59,'20',NULL,'Showdown','--Protagonist and antagonist close in on one another--physically or intellectually.','You Are Not Exceptional','The Original','Nacho restores her first backup: a nameless soldier.');
INSERT INTO "PK_tablature" VALUES (60,'21',NULL,'?','?','You Are Not Exceptional','Regression','Vivian becomes feral—rejects all identity.');
INSERT INTO "PK_tablature" VALUES (61,'21',NULL,'Unrecognized Arrival','--This scene is optional. The protagonist, unrecognized, arrives "home"--e.g., where story started. The protagonist looks may be transformed; the protagonist may be working undercover, etc.','You Are Not Exceptional','Speak Now, Myrtle','Myrtle speaks—breaking protocol to reach her.');
INSERT INTO "PK_tablature" VALUES (62,'21',NULL,'Ultiamte Confrontation','--The ultimate confrontation takes place in an exciting, extended scene. Any backstory and substory questions are answered.','You Are Not Exceptional','“I Choose Me.”','Vivian decides her origin doesn’t matter.');
INSERT INTO "PK_tablature" VALUES (63,'21',NULL,'Trump Card or False Claims','--The antagonist plays her/his last trump card--or another character makes false claims.','You Are Not Exceptional','Reset','She erases the last MODS copy herself.');
INSERT INTO "PK_tablature" VALUES (64,'22',NULL,'Antagonist Proposes Difficult Task','--The antagonist proposes a difficult task or ordeal to the protagonist to offer her/him a way out of the dilemma. Either choice means disaster.','You Are Not Exceptional','There Is No System','She finds peace without order or purpose.');
INSERT INTO "PK_tablature" VALUES (65,'22',NULL,'Protagonist Resolves Task','--In most cases the protagonist makes a choice for the greater good--but to their personal detriment. The biggest fight occurs here. All stops pulled out.','The Lustration','One Year of Silence','Vivian survives, alone, beneath a new sky.');
INSERT INTO "PK_tablature" VALUES (66,'22',NULL,'Protagonist Recognition','--The protagonist is recognized for their integrity. They may also be recognized after a long separation.','The Lustration','The Voice','A signal reaches her—neither MODS nor AN7L.');
INSERT INTO "PK_tablature" VALUES (67,'23',NULL,'Antagonist or False Claims Exposed','--The antagonist is revealed or false claims about the protagonist are exposed.','The Lustration','Origin Flag','It claims to come from Earth.');
INSERT INTO "PK_tablature" VALUES (68,'23',NULL,'Protagonist Given New Appearance','--The protagonist either undergoes essential change or is made more resolute to their initial self.','The Lustration','The New VANTA','She assembles one final suit—by hand.');
INSERT INTO "PK_tablature" VALUES (69,'23',NULL,'?','?','The Lustration','Listening','She weighs the offer in silence.');
INSERT INTO "PK_tablature" VALUES (70,'24',NULL,'Antagonist Punished','--The antagonist is punished in some way, e.g., shot, banished, commits suicide, or may be pardoned.','The Lustration','Reverie','Flashbacks and memories cascade with no dialogue.');
INSERT INTO "PK_tablature" VALUES (71,'24',NULL,'Story Outcome','--Plot loose ends are tied up','The Lustration','“No.”','Vivian responds to the signal. One word.');
INSERT INTO "PK_tablature" VALUES (72,'24',NULL,'Subplot Outcome','--Subplot relationship resolved.','The Lustration','The End of the Moon','Final shot: the Moon disappears. Cut to black.');
COMMIT;
